---
title: Geckoboard
timezone: UTC
collections:
  posts:
    title: Blog
    output: true
  integrations:
    title: Integrations
    output: true
  learn:
    title: Learn
    output: true
  uploads:
    title: Uploads
    output: false
defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
    layout: post
url: http://geckoboard.com
description: Use Geckoboard to build clear, effective data dashboards for your business
  that keep teams informed, motivated and aligned around your KPIs. Try for free.
permalink: pretty
exclude:
- Gemfile
- Gemfile.lock
- bower.json
- package.json
- config.codekit3
- README*
- LICENSE*
- CHANGELOG*
- node_modules
- ".gitignore"
- bower_components
gems:
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-feed
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
colophon: http://garethjohnsdesign.com
company: Geckoboard
email: support@geckoboard.com
google_site_verification: 
analytics: 
logo: 
per_page: 36
date_format: "%d %B %Y"
future: true
social:
  facebook: https://www.facebook.com/geckoboard
  linkedin: https://www.instagram.com/
  twitter: https://www.twitter.com/geckoboard
compress_html:
  comments:
  - "<!-- "
  - " -->"
  blanklines: true
  profile: false
ampdir: amp
book-a-demo: true
watch-a-demo-link: https://support.geckoboard.com/hc/en-us/articles/205646908
intercom-messenger: true